import tkinter as tk
from tkinter import ttk


class First_View():
    def __init__(self, Master):
        self.Frame=ttk.Frame(Master, padding=40)
        self.Frame.pack()
        self.style = ttk.Style()
        self.style.configure("BW.TLabel", foreground="black", background="white")
        self.Mesh=ttk.Frame(self.Frame, padding=20, style="BW.TLabel")
        self.Mesh.pack()
        self.Mesh_Label=ttk.Label(self.Mesh, text="Input domain and Num of SubIntervals", style="BW.TLabel")
        self.Mesh_Label.pack()
        self.A=tk.StringVar(self.Frame)
        self.B=tk.StringVar(self.Frame)
        self.N=tk.StringVar(self.Frame)
        self.g_A=tk.StringVar(self.Frame)
        self.g_B=tk.StringVar(self.Frame)
        self.bound_type=tk.StringVar()
        self.A_label=ttk.Label(self.Mesh, text="a", style="BW.TLabel")
        self.A_label.pack()
        self.input_A=ttk.Entry(self.Mesh,textvariable=self.A)
        self.input_A.pack()
        self.B_label=ttk.Label(self.Mesh, text="b", style="BW.TLabel")
        self.B_label.pack()
        self.input_B=ttk.Entry(self.Mesh,textvariable=self.B)
        self.input_B.pack()
        self.N_label=ttk.Label(self.Mesh, text="N", style="BW.TLabel")
        self.N_label.pack()
        self.input_N=ttk.Entry(self.Mesh,textvariable=self.N)
        self.input_N.pack()
        self.g_A_Label=ttk.Label(self.Mesh,text="g\u2090",style='BW.TLabel')
        self.g_A_Label.pack()
        self.input_g_A=ttk.Entry(self.Mesh,textvariable=self.g_A)
        self.input_g_A.pack()
        self.g_B_Label=ttk.Label(self.Mesh, text="g\u2099", style='BW.TLabel')
        self.g_B_Label.pack()
        self.input_g_B=ttk.Entry(self.Mesh, textvariable=self.g_B)
        self.input_g_B.pack()
        self.Bound_Label=ttk.Label(self.Mesh, text="Input the Bound Type", style='BW.TLabel')
        self.Bound_Label.pack()
        self.Bound_Select=ttk.Combobox(self.Mesh,textvariable=self.bound_type)
        self.Bound_Select['values']=['Dirichlet','Right Dirichlet','Left Dirichlet','Neither']
        self.Bound_Select['state']='readonly'
        self.Bound_Select.pack()
        self.A.set("0")
        self.B.set("1")
        self.N.set("256")
        self.g_A.set("0")
        self.g_B.set("0")
        self.bound_type.set("Dirichlet")
        self.mesh_button=tk.Button(self.Mesh, text="Enter")
        self.mesh_button.pack()